# Generated by Django 6.0.5 on 2026-07-22 10:53

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('publication_type', models.CharField(choices=[('journal', 'Journal Article'), ('conference', 'Conference Paper'), ('book', 'Book'), ('book_chapter', 'Book Chapter'), ('thesis', 'Thesis/Dissertation'), ('report', 'Report'), ('working_paper', 'Working Paper'), ('preprint', 'Preprint'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('published', 'Published'), ('in_press', 'In Press'), ('under_review', 'Under Review'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('journal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('journal_volume', models.CharField(blank=True, max_length=50, null=True)),
                ('journal_issue', models.CharField(blank=True, max_length=50, null=True)),
                ('pages', models.CharField(blank=True, max_length=50, null=True)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('issn', models.CharField(blank=True, max_length=20, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('acceptance_date', models.DateField(blank=True, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='publications/pdfs/%Y/%m/%d/')),
                ('citation_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'db_table': 'publications',
                'ordering': ['-publication_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not', 'Prefer not to say')], max_length=20, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('country_of_residence', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_bio', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('research_statement', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('teaching_interests', models.TextField(blank=True, null=True)),
                ('current_position', models.CharField(blank=True, max_length=255, null=True)),
                ('current_employer', models.CharField(blank=True, max_length=255, null=True)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('education', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('primary_research_area', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_research_areas', models.JSONField(blank=True, default=list)),
                ('research_keywords', models.JSONField(blank=True, default=list)),
                ('grants_awarded', models.JSONField(blank=True, default=list)),
                ('funding_sources', models.JSONField(blank=True, default=list)),
                ('awards', models.JSONField(blank=True, default=list)),
                ('honors', models.JSONField(blank=True, default=list)),
                ('professional_memberships', models.JSONField(blank=True, default=list)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('members_only', 'Members Only'), ('private', 'Private')], default='public', max_length=20)),
                ('show_email', models.BooleanField(default=False)),
                ('show_phone', models.BooleanField(default=False)),
                ('profile_completion', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('corresponding_author', models.BooleanField(default=False)),
                ('affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.publication')),
            ],
            options={
                'db_table': 'publication_authors',
                'ordering': ['order'],
                'unique_together': {('publication', 'author')},
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='members',
            field=models.ManyToManyField(related_name='publications', through='profiles.PublicationAuthor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ResearchInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_interests', to='profiles.researchinterest')),
            ],
            options={
                'verbose_name': 'Research Interest',
                'verbose_name_plural': 'Research Interests',
                'db_table': 'research_interests',
            },
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['title'], name='publication_title_2b1218_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['publication_type'], name='publication_publica_8278fe_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['status'], name='publication_status_c17c82_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['publication_date'], name='publication_publica_38baa4_idx'),
        ),
        migrations.AddIndex(
            model_name='researchinterest',
            index=models.Index(fields=['name'], name='research_in_name_2abe28_idx'),
        ),
        migrations.AddIndex(
            model_name='researchinterest',
            index=models.Index(fields=['category'], name='research_in_categor_6cab95_idx'),
        ),
    ]
