# Generated by Django 6.0.5 on 2026-07-22 10:53

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('webinar', 'Webinar'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('symposium', 'Symposium'), ('training', 'Training'), ('networking', 'Networking'), ('social', 'Social Event'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='draft', max_length=20)),
                ('organizer_name', models.CharField(max_length=255)),
                ('organizer_email', models.EmailField(max_length=254)),
                ('organizer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('organizer_website', models.URLField(blank=True, max_length=500, null=True)),
                ('is_virtual', models.BooleanField(default=False)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('virtual_link', models.URLField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('max_attendees', models.IntegerField(blank=True, null=True)),
                ('current_attendees', models.IntegerField(default=0)),
                ('requires_registration', models.BooleanField(default=True)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('registration_link', models.URLField(blank=True, max_length=500, null=True)),
                ('agenda', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('speakers', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('program', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='events/banners/%Y/%m/%d/')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='events/posters/%Y/%m/%d/')),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=50, null=True)),
                ('zoom_password', models.CharField(blank=True, max_length=50, null=True)),
                ('zoom_meeting_link', models.URLField(blank=True, max_length=500, null=True)),
                ('recording_url', models.URLField(blank=True, max_length=500, null=True)),
                ('recording_file', models.FileField(blank=True, null=True, upload_to='events/recordings/%Y/%m/%d/')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('view_count', models.IntegerField(default=0)),
                ('registration_count', models.IntegerField(default=0)),
                ('attendance_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('attendance_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('attended', 'Attended'), ('absent', 'Absent'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('payment_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('zoom_join_url', models.URLField(blank=True, max_length=500, null=True)),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=50, null=True)),
                ('zoom_password', models.CharField(blank=True, max_length=50, null=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='events/certificates/%Y/%m/%d/')),
                ('certificate_issued_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_submitted', models.BooleanField(default=False)),
                ('feedback_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('feedback_comment', models.TextField(blank=True, null=True)),
                ('feedback_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'db_table': 'event_registrations',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug'], name='events_slug_930801_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='events_event_t_c9f56c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='events_status_8890b6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date'], name='events_start_d_6c01fc_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['end_date'], name='events_end_dat_f7b00b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'attendance_status'], name='event_regis_event_i_31b811_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['user'], name='event_regis_user_id_c9d271_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'user')},
        ),
    ]
