# Generated by Django 6.0.5 on 2026-07-22 10:53

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('like_count', models.IntegerField(default=0)),
                ('report_count', models.IntegerField(default=0)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='communities.comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'community_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('community_type', models.CharField(choices=[('academic', 'Academic'), ('professional', 'Professional'), ('research', 'Research'), ('special_interest', 'Special Interest'), ('regional', 'Regional')], max_length=20)),
                ('access_type', models.CharField(choices=[('public', 'Public'), ('members_only', 'Members Only'), ('private', 'Private'), ('invite_only', 'Invite Only')], default='members_only', max_length=20)),
                ('member_count', models.IntegerField(default=0)),
                ('post_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('allow_member_posts', models.BooleanField(default=True)),
                ('require_moderation', models.BooleanField(default=False)),
                ('allow_attachments', models.BooleanField(default=True)),
                ('allow_discussions', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='communities/logos/%Y/%m/%d/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='communities/banners/%Y/%m/%d/')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_communities', to=settings.AUTH_USER_MODEL)),
                ('moderators', models.ManyToManyField(blank=True, related_name='moderated_communities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Communities',
                'db_table': 'communities',
                'ordering': ['-member_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('admin', 'Administrator')], default='member', max_length=20)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('notification_preferences', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='communities.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Member',
                'verbose_name_plural': 'Community Members',
                'db_table': 'community_members',
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('post_type', models.CharField(choices=[('discussion', 'Discussion'), ('question', 'Question'), ('announcement', 'Announcement'), ('resource', 'Resource'), ('event', 'Event'), ('poll', 'Poll')], default='discussion', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('pinned', 'Pinned'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='published', max_length=20)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='community/posts/%Y/%m/%d/')),
                ('poll_data', models.JSONField(blank=True, default=dict)),
                ('poll_votes', models.JSONField(blank=True, default=dict)),
                ('view_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='communities.community')),
            ],
            options={
                'verbose_name': 'Community Post',
                'verbose_name_plural': 'Community Posts',
                'db_table': 'community_posts',
                'ordering': ['-status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.communitypost')),
            ],
            options={
                'verbose_name': 'Community Like',
                'verbose_name_plural': 'Community Likes',
                'db_table': 'community_likes',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='communities.communitypost'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['slug'], name='communities_slug_e7aceb_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['community_type'], name='communities_communi_701543_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['access_type'], name='communities_access__e9a016_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['created_at'], name='communities_created_823b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymember',
            index=models.Index(fields=['community', 'role'], name='community_m_communi_77a31a_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymember',
            index=models.Index(fields=['last_active'], name='community_m_last_ac_918ec3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communitymember',
            unique_together={('community', 'user')},
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['community', 'created_at'], name='community_p_communi_24ed4d_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['author'], name='community_p_author__16beaf_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['status'], name='community_p_status_429e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['post_type'], name='community_p_post_ty_3991e5_idx'),
        ),
        migrations.AddIndex(
            model_name='communitylike',
            index=models.Index(fields=['user', 'post'], name='community_l_user_id_6446a3_idx'),
        ),
        migrations.AddIndex(
            model_name='communitylike',
            index=models.Index(fields=['user', 'comment'], name='community_l_user_id_3ee71a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communitylike',
            unique_together={('user', 'post', 'comment')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='community_c_post_id_2fbac0_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='community_c_author__da8e81_idx'),
        ),
    ]
