# Generated by Django 6.0.5 on 2026-07-22 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_type', models.CharField(choices=[('email', 'Email'), ('newsletter', 'Newsletter'), ('push', 'Push Notification'), ('sms', 'SMS')], max_length=20)),
                ('campaign_name', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('total_sent', models.IntegerField(default=0)),
                ('total_delivered', models.IntegerField(default=0)),
                ('total_opened', models.IntegerField(default=0)),
                ('total_clicked', models.IntegerField(default=0)),
                ('total_bounced', models.IntegerField(default=0)),
                ('total_unsubscribed', models.IntegerField(default=0)),
                ('total_spam', models.IntegerField(default=0)),
                ('open_rate', models.FloatField(default=0.0)),
                ('click_rate', models.FloatField(default=0.0)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Campaign Analytics',
                'verbose_name_plural': 'Campaign Analytics',
                'db_table': 'analytics_campaigns',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['campaign_type'], name='analytics_c_campaig_ddc3ae_idx'), models.Index(fields=['sent_at'], name='analytics_c_sent_at_5018ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=500, null=True)),
                ('referer_url', models.CharField(blank=True, max_length=500, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('time_on_page', models.IntegerField(default=0)),
                ('scroll_depth', models.IntegerField(default=0)),
                ('bounce', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'db_table': 'analytics_pageviews',
                'indexes': [models.Index(fields=['page_url'], name='analytics_p_page_ur_afa8aa_idx'), models.Index(fields=['created_at'], name='analytics_p_created_cf2780_idx'), models.Index(fields=['session_id'], name='analytics_p_session_b067c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logins', models.IntegerField(default=0)),
                ('profile_views', models.IntegerField(default=0)),
                ('content_views', models.IntegerField(default=0)),
                ('interactions', models.IntegerField(default=0)),
                ('posts_created', models.IntegerField(default=0)),
                ('comments_made', models.IntegerField(default=0)),
                ('collaborations_joined', models.IntegerField(default=0)),
                ('opportunities_applied', models.IntegerField(default=0)),
                ('events_attended', models.IntegerField(default=0)),
                ('resources_downloaded', models.IntegerField(default=0)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('average_session_length', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('engagement_score', models.IntegerField(default=0)),
                ('community_score', models.IntegerField(default=0)),
                ('research_score', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Analytics',
                'verbose_name_plural': 'User Activity Analytics',
                'db_table': 'analytics_user_activity',
                'indexes': [models.Index(fields=['user', 'date'], name='analytics_u_user_id_015ec2_idx'), models.Index(fields=['engagement_score'], name='analytics_u_engagem_1aab34_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
