# Generated by Django 6.0.5 on 2026-07-22 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('secret', models.CharField(blank=True, max_length=255, null=True)),
                ('events', models.JSONField(default=list, help_text='List of events to trigger this webhook')),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('last_response_code', models.IntegerField(blank=True, null=True)),
                ('failure_count', models.IntegerField(default=0)),
                ('retry_enabled', models.BooleanField(default=True)),
                ('max_retries', models.IntegerField(default=3)),
                ('retry_delay', models.IntegerField(default=300, help_text='Retry delay in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Webhook',
                'verbose_name_plural': 'API Webhooks',
                'db_table': 'api_webhooks',
            },
        ),
        migrations.CreateModel(
            name='APIWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('duration', models.FloatField(help_text='Response time in seconds')),
                ('success', models.BooleanField(default=False)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.apiwebhook')),
            ],
            options={
                'verbose_name': 'API Webhook Log',
                'verbose_name_plural': 'API Webhook Logs',
                'db_table': 'api_webhook_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('response_time', models.FloatField(help_text='Response time in seconds')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Access Log',
                'verbose_name_plural': 'API Access Logs',
                'db_table': 'api_access_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='api_access__user_id_27ebda_idx'), models.Index(fields=['endpoint'], name='api_access__endpoin_fc2f72_idx'), models.Index(fields=['status_code'], name='api_access__status__05680b_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(help_text='Token name for identification', max_length=255)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Custom permissions for this token')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.TextField(blank=True, null=True)),
                ('rate_limit', models.IntegerField(default=1000, help_text='Requests per day')),
                ('requests_today', models.IntegerField(default=0)),
                ('last_reset', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Token',
                'verbose_name_plural': 'API Tokens',
                'db_table': 'api_tokens',
                'indexes': [models.Index(fields=['user', 'is_active'], name='api_tokens_user_id_c0d9c9_idx'), models.Index(fields=['token'], name='api_tokens_token_8d7e16_idx'), models.Index(fields=['expires_at'], name='api_tokens_expires_a047d2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='apiwebhook',
            index=models.Index(fields=['user', 'is_active'], name='api_webhook_user_id_2ad960_idx'),
        ),
        migrations.AddIndex(
            model_name='apiwebhook',
            index=models.Index(fields=['url'], name='api_webhook_url_712cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='apiwebhooklog',
            index=models.Index(fields=['webhook', 'created_at'], name='api_webhook_webhook_8257c1_idx'),
        ),
        migrations.AddIndex(
            model_name='apiwebhooklog',
            index=models.Index(fields=['success'], name='api_webhook_success_64335a_idx'),
        ),
    ]
