# Generated by Django 6.0.5 on 2026-07-22 10:53

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('collaboration_type', models.CharField(choices=[('research', 'Research Collaboration'), ('co_authorship', 'Co-authorship'), ('data_collection', 'Data Collection'), ('peer_review', 'Peer Review'), ('mentorship', 'Mentorship'), ('funding', 'Funding Collaboration'), ('equipment', 'Equipment Sharing'), ('training', 'Training/Workshop'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('expired', 'Expired')], default='open', max_length=20)),
                ('is_open', models.BooleanField(default=True)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('required_expertise', models.JSONField(blank=True, default=list)),
                ('required_institutions', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_weeks', models.IntegerField(blank=True, null=True)),
                ('is_remote', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('has_funding', models.BooleanField(default=False)),
                ('funding_details', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('view_count', models.IntegerField(default=0)),
                ('application_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_requests', to=settings.AUTH_USER_MODEL)),
                ('target_users', models.ManyToManyField(blank=True, related_name='targeted_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collaboration Request',
                'verbose_name_plural': 'Collaboration Requests',
                'db_table': 'collaboration_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaborationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', django_ckeditor_5.fields.CKEditor5Field()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_collaboration_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_collaboration_messages', to=settings.AUTH_USER_MODEL)),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='collaborations.collaborationrequest')),
            ],
            options={
                'verbose_name': 'Collaboration Message',
                'verbose_name_plural': 'Collaboration Messages',
                'db_table': 'collaboration_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaborationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', django_ckeditor_5.fields.CKEditor5Field()),
                ('skills', models.JSONField(blank=True, default=list)),
                ('experience', models.TextField(blank=True, null=True)),
                ('availability', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='collaborations.collaborationrequest')),
            ],
            options={
                'verbose_name': 'Collaboration Application',
                'verbose_name_plural': 'Collaboration Applications',
                'db_table': 'collaboration_applications',
            },
        ),
        migrations.CreateModel(
            name='SupervisorMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matching_type', models.CharField(choices=[('student', 'Student Seeking Supervisor'), ('supervisor', 'Supervisor Seeking Student'), ('mutual', 'Mutual Interest')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('research_area', models.CharField(max_length=255)),
                ('research_interest', models.TextField()),
                ('specific_topic', models.CharField(blank=True, max_length=500, null=True)),
                ('preferred_institution', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_location', models.CharField(blank=True, max_length=255, null=True)),
                ('availability_start', models.DateField(blank=True, null=True)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('match_reasons', models.JSONField(blank=True, default=list)),
                ('supervisor_availability', models.TextField(blank=True, null=True)),
                ('supervision_capacity', models.IntegerField(default=1)),
                ('current_students', models.IntegerField(default=0)),
                ('communication_history', models.JSONField(blank=True, default=list)),
                ('last_communication', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_matches', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supervisor Match',
                'verbose_name_plural': 'Supervisor Matches',
                'db_table': 'supervisor_matches',
            },
        ),
        migrations.AddIndex(
            model_name='collaborationrequest',
            index=models.Index(fields=['status'], name='collaborati_status_a86b83_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborationrequest',
            index=models.Index(fields=['collaboration_type'], name='collaborati_collabo_0f9f9f_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborationrequest',
            index=models.Index(fields=['created_at'], name='collaborati_created_0e726e_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborationrequest',
            index=models.Index(fields=['requested_by', 'status'], name='collaborati_request_a3a989_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborationmessage',
            index=models.Index(fields=['collaboration', 'created_at'], name='collaborati_collabo_94aaec_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborationmessage',
            index=models.Index(fields=['sender', 'receiver'], name='collaborati_sender__d27fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborationmessage',
            index=models.Index(fields=['is_read'], name='collaborati_is_read_7d7531_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborationapplication',
            index=models.Index(fields=['collaboration', 'status'], name='collaborati_collabo_e16587_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborationapplication',
            index=models.Index(fields=['applicant'], name='collaborati_applica_4d31ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collaborationapplication',
            unique_together={('collaboration', 'applicant')},
        ),
        migrations.AddIndex(
            model_name='supervisormatching',
            index=models.Index(fields=['student', 'status'], name='supervisor__student_c5da2c_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisormatching',
            index=models.Index(fields=['supervisor', 'status'], name='supervisor__supervi_fb2cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisormatching',
            index=models.Index(fields=['match_score'], name='supervisor__match_s_c0b802_idx'),
        ),
    ]
