# Generated by Django 6.0.5 on 2026-07-23 10:30

import accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('requested_role', models.CharField(choices=[('super_admin', 'Super Administrator'), ('admin', 'Administrator'), ('executive', 'Executive Committee'), ('moderator', 'Community Moderator'), ('verified_member', 'Verified Member'), ('basic_member', 'Basic Member'), ('prospective_member', 'Prospective Member'), ('alumni', 'Alumni'), ('researcher', 'Researcher'), ('partner', 'Institutional Partner'), ('guest', 'Guest')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_info', 'Needs More Information')], default='pending', max_length=20)),
                ('motivation', models.TextField()),
                ('experience', models.TextField(blank=True, null=True)),
                ('publications', models.TextField(blank=True, null=True)),
                ('references', models.JSONField(blank=True, default=list)),
                ('cv', models.FileField(blank=True, null=True, upload_to='applications/cv/%Y/%m/%d/')),
                ('recommendation_letter', models.FileField(blank=True, null=True, upload_to='applications/recommendations/%Y/%m/%d/')),
                ('additional_documents', models.FileField(blank=True, null=True, upload_to='applications/additional/%Y/%m/%d/')),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registration Application',
                'verbose_name_plural': 'Registration Applications',
                'db_table': 'registration_applications',
            },
        ),
        migrations.CreateModel(
            name='RoleChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(choices=[('super_admin', 'Super Administrator'), ('admin', 'Administrator'), ('executive', 'Executive Committee'), ('moderator', 'Community Moderator'), ('verified_member', 'Verified Member'), ('basic_member', 'Basic Member'), ('prospective_member', 'Prospective Member'), ('alumni', 'Alumni'), ('researcher', 'Researcher'), ('partner', 'Institutional Partner'), ('guest', 'Guest')], max_length=30)),
                ('current_role', models.CharField(choices=[('super_admin', 'Super Administrator'), ('admin', 'Administrator'), ('executive', 'Executive Committee'), ('moderator', 'Community Moderator'), ('verified_member', 'Verified Member'), ('basic_member', 'Basic Member'), ('prospective_member', 'Prospective Member'), ('alumni', 'Alumni'), ('researcher', 'Researcher'), ('partner', 'Institutional Partner'), ('guest', 'Guest')], max_length=30)),
                ('reason', models.TextField()),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='role_changes/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role Change Request',
                'verbose_name_plural': 'Role Change Requests',
                'db_table': 'role_change_requests',
            },
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_ty_578f8f_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='academic_level',
            field=models.CharField(blank=True, choices=[('masters', "Master's Student"), ('phd', 'PhD Candidate'), ('postdoc', 'Postdoctoral Researcher'), ('early_career', 'Early Career Researcher'), ('senior_researcher', 'Senior Researcher'), ('professor', 'Professor'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='available_for_collaboration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='citation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='collaboration_interests',
            field=models.JSONField(blank=True, default=accounts.models.default_collaboration_interests),
        ),
        migrations.AddField(
            model_name='user',
            name='collaboration_preferences',
            field=models.JSONField(blank=True, default=accounts.models.default_collaboration_preferences),
        ),
        migrations.AddField(
            model_name='user',
            name='current_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='executive_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='executive_tenure_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='executive_tenure_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='h_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/ids/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_document_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='institutional_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_mentee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_fee_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mentee_goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mentor_areas',
            field=models.JSONField(blank=True, default=accounts.models.default_mentor_areas),
        ),
        migrations.AddField(
            model_name='user',
            name='mentor_id',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_mentor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='partner_organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='partner_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='publication_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('banned', 'Banned'), ('requires_verification', 'Requires Verification')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='research_keywords',
            field=models.JSONField(blank=True, default=accounts.models.default_research_keywords),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrator'), ('admin', 'Administrator'), ('executive', 'Executive Committee'), ('moderator', 'Community Moderator'), ('verified_member', 'Verified Member'), ('basic_member', 'Basic Member'), ('prospective_member', 'Prospective Member'), ('alumni', 'Alumni'), ('researcher', 'Researcher'), ('partner', 'Institutional Partner'), ('guest', 'Guest')], default='basic_member', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='security_questions',
            field=models.JSONField(blank=True, default=accounts.models.default_security_questions),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Africa/Nairobi', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=accounts.models.default_notification_preferences),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('registration', 'Registration'), ('profile_update', 'Profile Update'), ('role_change', 'Role Change'), ('member_verification', 'Member Verification'), ('community_join', 'Community Join'), ('event_registration', 'Event Registration'), ('opportunity_apply', 'Opportunity Apply'), ('resource_download', 'Resource Download'), ('forum_post', 'Forum Post'), ('collaboration_request', 'Collaboration Request'), ('payment', 'Payment'), ('mentorship_request', 'Mentorship Request'), ('report_submitted', 'Report Submitted'), ('profile_view', 'Profile View')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['registration_status'], name='users_registr_6de26c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['academic_level'], name='users_academi_37b7b1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active_member'], name='users_is_acti_2f5c18_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
        migrations.AddField(
            model_name='registrationapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_applications_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrationapplication',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolechangerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_change_requests_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolechangerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_change_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='user',
            name='degree_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddIndex(
            model_name='registrationapplication',
            index=models.Index(fields=['status'], name='registratio_status_2bf68a_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationapplication',
            index=models.Index(fields=['requested_role'], name='registratio_request_9761e3_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationapplication',
            index=models.Index(fields=['created_at'], name='registratio_created_d29989_idx'),
        ),
        migrations.AddIndex(
            model_name='rolechangerequest',
            index=models.Index(fields=['status'], name='role_change_status_81cf92_idx'),
        ),
        migrations.AddIndex(
            model_name='rolechangerequest',
            index=models.Index(fields=['user', 'created_at'], name='role_change_user_id_46be48_idx'),
        ),
    ]
