# Generated by Django 6.0.5 on 2026-07-22 10:53

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('thread_count', models.IntegerField(default=0)),
                ('post_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_moderation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Forum Category',
                'verbose_name_plural': 'Forum Categories',
                'db_table': 'forum_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ForumReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('like_count', models.IntegerField(default=0)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_replies', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forums.forumreply')),
            ],
            options={
                'verbose_name': 'Forum Reply',
                'verbose_name_plural': 'Forum Replies',
                'db_table': 'forum_replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pinned', 'Pinned'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='open', max_length=20)),
                ('is_sticky', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('reply_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_threads', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='forums.forumcategory')),
            ],
            options={
                'verbose_name': 'Forum Thread',
                'verbose_name_plural': 'Forum Threads',
                'db_table': 'forum_threads',
                'ordering': ['-is_sticky', '-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ForumReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('spam', 'Spam'), ('offensive', 'Offensive Content'), ('harassment', 'Harassment'), ('copyright', 'Copyright Violation'), ('duplicate', 'Duplicate'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forums.forumreply')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forums.forumthread')),
            ],
            options={
                'verbose_name': 'Forum Report',
                'verbose_name_plural': 'Forum Reports',
                'db_table': 'forum_reports',
            },
        ),
        migrations.AddField(
            model_name='forumreply',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forums.forumthread'),
        ),
        migrations.CreateModel(
            name='ForumLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_type', models.CharField(choices=[('thread', 'Thread'), ('reply', 'Reply')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_likes', to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='forums.forumreply')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='forums.forumthread')),
            ],
            options={
                'db_table': 'forum_likes',
            },
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['category', 'created_at'], name='forum_threa_categor_3967d9_idx'),
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['author'], name='forum_threa_author__5d73b5_idx'),
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['status'], name='forum_threa_status_4c87a8_idx'),
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['last_activity'], name='forum_threa_last_ac_c174f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='forumlike',
            unique_together={('user', 'thread', 'reply')},
        ),
    ]
