# Generated by Django 6.0.5 on 2026-07-22 10:53

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('opportunity_type', models.CharField(choices=[('scholarship', 'Scholarship'), ('phd_position', 'PhD Position'), ('masters_position', "Master's Position"), ('postdoc', 'Postdoctoral Fellowship'), ('conference', 'Conference'), ('call_for_papers', 'Call for Papers'), ('grant', 'Grant'), ('job', 'Job'), ('internship', 'Internship'), ('training', 'Training/Workshop'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('expired', 'Expired'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_website', models.URLField(blank=True, max_length=500, null=True)),
                ('organization_logo', models.ImageField(blank=True, null=True, upload_to='opportunities/logos/%Y/%m/%d/')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('application_deadline', models.DateTimeField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('has_funding', models.BooleanField(default=False)),
                ('funding_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('funding_details', models.TextField(blank=True, null=True)),
                ('eligibility_criteria', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('required_qualifications', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('preferred_qualifications', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('application_requirements', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('required_documents', models.JSONField(blank=True, default=list)),
                ('application_url', models.URLField(blank=True, max_length=500, null=True)),
                ('application_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('application_instructions', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('disciplines', models.JSONField(blank=True, default=list)),
                ('view_count', models.IntegerField(default=0)),
                ('application_count', models.IntegerField(default=0)),
                ('save_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_opportunities', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'db_table': 'opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('message', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_applications', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.opportunity')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications_opp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opportunity Application',
                'verbose_name_plural': 'Opportunity Applications',
                'db_table': 'opportunity_applications',
            },
        ),
        migrations.CreateModel(
            name='OpportunitySave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='opportunities.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'opportunity_saves',
            },
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['opportunity_type'], name='opportuniti_opportu_b8dd5f_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['status'], name='opportuniti_status_019aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['application_deadline'], name='opportuniti_applica_e47269_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['created_at'], name='opportuniti_created_3102e4_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['country'], name='opportuniti_country_42165f_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityapplication',
            index=models.Index(fields=['opportunity', 'status'], name='opportunity_opportu_270cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityapplication',
            index=models.Index(fields=['applicant'], name='opportunity_applica_61fca3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='opportunityapplication',
            unique_together={('opportunity', 'applicant')},
        ),
        migrations.AlterUniqueTogether(
            name='opportunitysave',
            unique_together={('opportunity', 'user')},
        ),
    ]
