# Generated by Django 6.0.5 on 2026-07-22 10:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('student', 'Student'), ('researcher', 'Researcher'), ('professional', 'Professional'), ('alumni', 'Alumni')], default='student', max_length=20)),
                ('membership_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('student_id', models.ImageField(blank=True, null=True, upload_to='members/ids/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('admission_letter', models.FileField(blank=True, null=True, upload_to='members/admissions/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('transcript', models.FileField(blank=True, null=True, upload_to='members/transcripts/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('digital_card', models.ImageField(blank=True, null=True, upload_to='members/cards/%Y/%m/%d/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='members/qrcodes/%Y/%m/%d/')),
                ('card_issued_at', models.DateTimeField(blank=True, null=True)),
                ('card_expires_at', models.DateTimeField(blank=True, null=True)),
                ('student_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('year_of_study', models.IntegerField(blank=True, null=True)),
                ('expected_graduation_year', models.IntegerField(blank=True, null=True)),
                ('thesis_title', models.CharField(blank=True, max_length=500, null=True)),
                ('thesis_abstract', models.TextField(blank=True, null=True)),
                ('supervisor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supervisor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('publication_count', models.IntegerField(default=0)),
                ('citation_count', models.IntegerField(default=0)),
                ('h_index', models.IntegerField(default=0)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('expertise_areas', models.JSONField(blank=True, default=list)),
                ('programming_languages', models.JSONField(blank=True, default=list)),
                ('research_methodologies', models.JSONField(blank=True, default=list)),
                ('collaboration_interests', models.JSONField(blank=True, default=list)),
                ('mentoring_interests', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='MemberActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('profile_view', 'Profile View'), ('profile_update', 'Profile Update'), ('community_join', 'Community Join'), ('community_post', 'Community Post'), ('event_registration', 'Event Registration'), ('event_attendance', 'Event Attendance'), ('opportunity_apply', 'Opportunity Apply'), ('resource_download', 'Resource Download'), ('forum_post', 'Forum Post'), ('collaboration_request', 'Collaboration Request'), ('collaboration_accept', 'Collaboration Accept'), ('publication_add', 'Publication Added'), ('skill_update', 'Skill Updated')], max_length=50)),
                ('activity_description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='members.member')),
            ],
            options={
                'verbose_name': 'Member Activity',
                'verbose_name_plural': 'Member Activities',
                'db_table': 'member_activities',
            },
        ),
        migrations.CreateModel(
            name='MemberVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(default='initial', max_length=50)),
                ('request_notes', models.TextField(blank=True, null=True)),
                ('documents', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('review_decision', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('additional_info', 'Additional Information Required')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='members.member')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Verification Request',
                'verbose_name_plural': 'Member Verification Requests',
                'db_table': 'member_verification_requests',
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['membership_number'], name='members_members_3b8303_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['verification_status'], name='members_verific_fa00cd_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['membership_type'], name='members_members_aba64f_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['user', 'verification_status'], name='members_user_id_98f002_idx'),
        ),
        migrations.AddIndex(
            model_name='memberactivity',
            index=models.Index(fields=['member', 'created_at'], name='member_acti_member__6e620a_idx'),
        ),
        migrations.AddIndex(
            model_name='memberactivity',
            index=models.Index(fields=['activity_type'], name='member_acti_activit_3f69ac_idx'),
        ),
        migrations.AddIndex(
            model_name='memberverificationrequest',
            index=models.Index(fields=['member', 'review_decision'], name='member_veri_member__c2b9e3_idx'),
        ),
        migrations.AddIndex(
            model_name='memberverificationrequest',
            index=models.Index(fields=['created_at'], name='member_veri_created_129e19_idx'),
        ),
    ]
