# Generated by Django 6.0.5 on 2026-07-22 10:53

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
                ('resource_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='resources.resourcecategory')),
            ],
            options={
                'verbose_name': 'Resource Category',
                'verbose_name_plural': 'Resource Categories',
                'db_table': 'resource_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('resource_type', models.CharField(choices=[('guide', 'Guide'), ('template', 'Template'), ('tutorial', 'Tutorial'), ('tool', 'Tool'), ('dataset', 'Dataset'), ('ebook', 'E-Book'), ('presentation', 'Presentation'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], max_length=20)),
                ('access_type', models.CharField(choices=[('public', 'Public'), ('members_only', 'Members Only'), ('premium', 'Premium')], default='public', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/files/%Y/%m/%d/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='resources/covers/%Y/%m/%d/')),
                ('file_size', models.CharField(blank=True, max_length=50, null=True)),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('external_url', models.URLField(blank=True, max_length=500, null=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_latest_version', models.BooleanField(default=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('view_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_resources', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='resources', to='resources.resourcecategory')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'db_table': 'resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resource_downloads',
            },
        ),
        migrations.CreateModel(
            name='ResourceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resource_ratings',
            },
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['slug'], name='resources_slug_90bf4e_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['resource_type'], name='resources_resourc_dcd1e3_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['access_type'], name='resources_access__1acfcc_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['created_at'], name='resources_created_3c8efb_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['is_featured'], name='resources_is_feat_c45a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcedownload',
            index=models.Index(fields=['resource', 'downloaded_at'], name='resource_do_resourc_27e9b3_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcedownload',
            index=models.Index(fields=['user'], name='resource_do_user_id_993cc6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcerating',
            unique_together={('resource', 'user')},
        ),
    ]
